# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/annotated_axis_aligned_2d_box.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
require 'gz/msgs/axis_aligned_2d_box_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.AnnotatedAxisAligned2DBox" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :box, :message, 2, "gz.msgs.AxisAligned2DBox"
    optional :label, :uint32, 3
  end
end

module Gz
  module Msgs
    AnnotatedAxisAligned2DBox = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.AnnotatedAxisAligned2DBox").msgclass
  end
end
