# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/dvl_kinematic_estimate.proto

require 'google/protobuf'

require 'gz/msgs/vector3d_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.DVLKinematicEstimate" do
    optional :reference, :enum, 1, "gz.msgs.DVLKinematicEstimate.ReferenceType"
    optional :mean, :message, 2, "gz.msgs.Vector3d"
    repeated :covariance, :double, 3
  end
  add_enum "gz.msgs.DVLKinematicEstimate.ReferenceType" do
    value :DVL_REFERENCE_UNSPECIFIED, 0
    value :DVL_REFERENCE_EARTH, 1
    value :DVL_REFERENCE_SHIP, 2
  end
end

module Gz
  module Msgs
    DVLKinematicEstimate = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.DVLKinematicEstimate").msgclass
    DVLKinematicEstimate::ReferenceType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.DVLKinematicEstimate.ReferenceType").enummodule
  end
end
