# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/entity_wrench.proto

require 'google/protobuf'

require 'gz/msgs/entity_pb'
require 'gz/msgs/header_pb'
require 'gz/msgs/wrench_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.EntityWrench" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :entity, :message, 2, "gz.msgs.Entity"
    optional :wrench, :message, 3, "gz.msgs.Wrench"
  end
end

module Gz
  module Msgs
    EntityWrench = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.EntityWrench").msgclass
  end
end
