# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/imu_sensor.proto

require 'google/protobuf'

require 'gz/msgs/sensor_noise_pb'
require 'gz/msgs/header_pb'
require 'gz/msgs/vector3d_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.IMUSensor" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :angular_velocity, :message, 2, "gz.msgs.IMUSensor.AngularVelocity"
    optional :linear_acceleration, :message, 3, "gz.msgs.IMUSensor.LinearAcceleration"
    optional :orientation_ref_frame, :message, 4, "gz.msgs.IMUSensor.OrientationReferenceFrame"
  end
  add_message "gz.msgs.IMUSensor.AngularVelocity" do
    optional :x_noise, :message, 1, "gz.msgs.SensorNoise"
    optional :y_noise, :message, 2, "gz.msgs.SensorNoise"
    optional :z_noise, :message, 3, "gz.msgs.SensorNoise"
  end
  add_message "gz.msgs.IMUSensor.LinearAcceleration" do
    optional :x_noise, :message, 1, "gz.msgs.SensorNoise"
    optional :y_noise, :message, 2, "gz.msgs.SensorNoise"
    optional :z_noise, :message, 3, "gz.msgs.SensorNoise"
  end
  add_message "gz.msgs.IMUSensor.OrientationReferenceFrame" do
    optional :localization, :string, 1
    optional :custom_rpy, :message, 2, "gz.msgs.Vector3d"
    optional :custom_rpy_parent_frame, :string, 3
    optional :gravity_dir_x, :message, 4, "gz.msgs.Vector3d"
    optional :gravity_dir_x_parent_frame, :string, 5
  end
end

module Gz
  module Msgs
    IMUSensor = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.IMUSensor").msgclass
    IMUSensor::AngularVelocity = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.IMUSensor.AngularVelocity").msgclass
    IMUSensor::LinearAcceleration = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.IMUSensor.LinearAcceleration").msgclass
    IMUSensor::OrientationReferenceFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.IMUSensor.OrientationReferenceFrame").msgclass
  end
end
