# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/joy.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Joy" do
    optional :header, :message, 1, "gz.msgs.Header"
    repeated :axes, :float, 2
    repeated :buttons, :int32, 3
  end
end

module Gz
  module Msgs
    Joy = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Joy").msgclass
  end
end
