# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/rest_logout.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.RestLogout" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :id, :uint32, 2
    optional :url, :string, 3
  end
end

module Gz
  module Msgs
    RestLogout = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.RestLogout").msgclass
  end
end
