# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/user_cmd.proto

require 'google/protobuf'

require 'gz/msgs/light_pb'
require 'gz/msgs/model_pb'
require 'gz/msgs/world_control_pb'
require 'gz/msgs/wrench_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.UserCmd" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :id, :uint32, 2
    optional :description, :string, 3
    optional :type, :enum, 4, "gz.msgs.UserCmd.Type"
    repeated :model, :message, 5, "gz.msgs.Model"
    repeated :light, :message, 6, "gz.msgs.Light"
    optional :entity_name, :string, 7
    optional :world_control, :message, 8, "gz.msgs.WorldControl"
    optional :wrench, :message, 9, "gz.msgs.Wrench"
  end
  add_enum "gz.msgs.UserCmd.Type" do
    value :MOVING, 0
    value :WORLD_CONTROL, 1
    value :WRENCH, 2
    value :SCALING, 3
  end
end

module Gz
  module Msgs
    UserCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.UserCmd").msgclass
    UserCmd::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.UserCmd.Type").enummodule
  end
end
