# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/world_control.proto

require 'google/protobuf'

require 'gz/msgs/world_reset_pb'
require 'gz/msgs/header_pb'
require 'gz/msgs/time_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.WorldControl" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :pause, :bool, 2
    optional :step, :bool, 3
    optional :multi_step, :uint32, 4
    optional :reset, :message, 5, "gz.msgs.WorldReset"
    optional :seed, :uint32, 6
    optional :run_to_sim_time, :message, 7, "gz.msgs.Time"
  end
end

module Gz
  module Msgs
    WorldControl = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.WorldControl").msgclass
  end
end
