/*
 * Copyright (C) 2022 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* Config.hh. Generated by CMake for gz-fuel_tools9. */

#ifndef GZ_FUEL_TOOLS_CONFIG_HH_
#define GZ_FUEL_TOOLS_CONFIG_HH_

/* Version number */
#define GZ_FUEL_TOOLS_MAJOR_VERSION 9
#define GZ_FUEL_TOOLS_MINOR_VERSION 0
#define GZ_FUEL_TOOLS_PATCH_VERSION 0

#define GZ_FUEL_TOOLS_VERSION "9.0"
#define GZ_FUEL_TOOLS_VERSION_FULL "9.0.0"

#define GZ_FUEL_TOOLS_VERSION_HEADER "Gazebo Fuel Tools, version 9.0.0\nCopyright (C) 2017 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

#define GZ_FUEL_INITIAL_CONFIG_PATH "/home/julia/workspace/install/share/ignition/fuel_tools9/"

#endif
