# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/clock.proto

require 'google/protobuf'

require 'gz/msgs/time_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Clock" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :system, :message, 2, "gz.msgs.Time"
    optional :real, :message, 3, "gz.msgs.Time"
    optional :sim, :message, 4, "gz.msgs.Time"
  end
end

module Gz
  module Msgs
    Clock = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Clock").msgclass
  end
end
