# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/density.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Density" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :density, :double, 2
  end
end

module Gz
  module Msgs
    Density = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Density").msgclass
  end
end
