# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/gui.proto

require 'google/protobuf'

require 'gz/msgs/gui_camera_pb'
require 'gz/msgs/plugin_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.GUI" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :fullscreen, :bool, 2
    optional :camera, :message, 3, "gz.msgs.GUICamera"
    repeated :plugin, :message, 4, "gz.msgs.Plugin"
  end
end

module Gz
  module Msgs
    GUI = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.GUI").msgclass
  end
end
