# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/logical_camera_sensor.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.LogicalCameraSensor" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :near_clip, :double, 2
    optional :far_clip, :double, 3
    optional :horizontal_fov, :double, 4
    optional :aspect_ratio, :double, 5
  end
end

module Gz
  module Msgs
    LogicalCameraSensor = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.LogicalCameraSensor").msgclass
  end
end
