# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/pid.proto

require 'google/protobuf'

require 'gz/msgs/double_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.PID" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :target_optional, :message, 2, "gz.msgs.Double"
    optional :p_gain_optional, :message, 3, "gz.msgs.Double"
    optional :i_gain_optional, :message, 4, "gz.msgs.Double"
    optional :d_gain_optional, :message, 5, "gz.msgs.Double"
    optional :i_max_optional, :message, 6, "gz.msgs.Double"
    optional :i_min_optional, :message, 7, "gz.msgs.Double"
    optional :limit_optional, :message, 8, "gz.msgs.Double"
  end
end

module Gz
  module Msgs
    PID = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.PID").msgclass
  end
end
