# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/pose_with_covariance.proto

require 'google/protobuf'

require 'gz/msgs/float_v_pb'
require 'gz/msgs/pose_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.PoseWithCovariance" do
    optional :pose, :message, 1, "gz.msgs.Pose"
    optional :covariance, :message, 2, "gz.msgs.Float_V"
  end
end

module Gz
  module Msgs
    PoseWithCovariance = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.PoseWithCovariance").msgclass
  end
end
