# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/scene.proto

require 'google/protobuf'

require 'gz/msgs/color_pb'
require 'gz/msgs/fog_pb'
require 'gz/msgs/sky_pb'
require 'gz/msgs/light_pb'
require 'gz/msgs/joint_pb'
require 'gz/msgs/material_pb'
require 'gz/msgs/model_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Scene" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :name, :string, 2
    optional :ambient, :message, 3, "gz.msgs.Color"
    optional :background, :message, 4, "gz.msgs.Color"
    optional :sky, :message, 5, "gz.msgs.Sky"
    optional :shadows, :bool, 6
    optional :fog, :message, 7, "gz.msgs.Fog"
    optional :grid, :bool, 8
    repeated :model, :message, 9, "gz.msgs.Model"
    repeated :light, :message, 10, "gz.msgs.Light"
    repeated :joint, :message, 11, "gz.msgs.Joint"
    optional :origin_visual, :bool, 12
    optional :shadow_caster_material_script, :message, 13, "gz.msgs.Material.Script"
  end
end

module Gz
  module Msgs
    Scene = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Scene").msgclass
  end
end
