# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/uint64_v.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.UInt64_V" do
    optional :header, :message, 1, "gz.msgs.Header"
    repeated :data, :uint64, 2
  end
end

module Gz
  module Msgs
    UInt64_V = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.UInt64_V").msgclass
  end
end
