# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/visual.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
require 'gz/msgs/pose_pb'
require 'gz/msgs/geometry_pb'
require 'gz/msgs/material_pb'
require 'gz/msgs/plugin_pb'
require 'gz/msgs/vector3d_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Visual" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :name, :string, 2
    optional :id, :uint32, 3
    optional :parent_name, :string, 4
    optional :parent_id, :uint32, 5
    optional :cast_shadows, :bool, 6
    optional :transparency, :double, 7
    optional :laser_retro, :double, 8
    optional :pose, :message, 9, "gz.msgs.Pose"
    optional :geometry, :message, 10, "gz.msgs.Geometry"
    optional :material, :message, 11, "gz.msgs.Material"
    optional :visible, :bool, 12
    optional :delete_me, :bool, 13
    optional :is_static, :bool, 14
    repeated :plugin, :message, 15, "gz.msgs.Plugin"
    optional :scale, :message, 16, "gz.msgs.Vector3d"
    optional :meta, :message, 17, "gz.msgs.Visual.Meta"
    optional :type, :enum, 18, "gz.msgs.Visual.Type"
  end
  add_message "gz.msgs.Visual.Meta" do
    optional :layer, :int32, 1
  end
  add_enum "gz.msgs.Visual.Type" do
    value :ENTITY, 0
    value :MODEL, 1
    value :LINK, 2
    value :VISUAL, 3
    value :COLLISION, 4
    value :SENSOR, 5
    value :GUI, 6
    value :PHYSICS, 7
  end
end

module Gz
  module Msgs
    Visual = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Visual").msgclass
    Visual::Meta = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Visual.Meta").msgclass
    Visual::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Visual.Type").enummodule
  end
end
