# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/wind.proto

require 'google/protobuf'

require 'gz/msgs/vector3d_pb'
require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.Wind" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :linear_velocity, :message, 2, "gz.msgs.Vector3d"
    optional :enable_wind, :bool, 3
  end
end

module Gz
  module Msgs
    Wind = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.Wind").msgclass
  end
end
