# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/world_modify.proto

require 'google/protobuf'

require 'gz/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gz.msgs.WorldModify" do
    optional :header, :message, 1, "gz.msgs.Header"
    optional :world_name, :string, 2
    optional :remove, :bool, 3
    optional :create, :bool, 4
    optional :cloned, :bool, 5
    optional :cloned_uri, :string, 6
  end
end

module Gz
  module Msgs
    WorldModify = Google::Protobuf::DescriptorPool.generated_pool.lookup("gz.msgs.WorldModify").msgclass
  end
end
