
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/any.proto

#ifndef gz_msgs_any
#define gz_msgs_any

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/any.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Any> AnyUniquePtr;
typedef std::unique_ptr<const Any> ConstAnyUniquePtr;
typedef std::shared_ptr<Any> AnySharedPtr;
typedef std::shared_ptr<const Any> ConstAnySharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_any
