
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/axis.proto

#ifndef gz_msgs_axis
#define gz_msgs_axis

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/axis.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Axis> AxisUniquePtr;
typedef std::unique_ptr<const Axis> ConstAxisUniquePtr;
typedef std::shared_ptr<Axis> AxisSharedPtr;
typedef std::shared_ptr<const Axis> ConstAxisSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_axis
