
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/double_v.proto

#ifndef gz_msgs_double_v
#define gz_msgs_double_v

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/double_v.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Double_V> Double_VUniquePtr;
typedef std::unique_ptr<const Double_V> ConstDouble_VUniquePtr;
typedef std::shared_ptr<Double_V> Double_VSharedPtr;
typedef std::shared_ptr<const Double_V> ConstDouble_VSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_double_v
