
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/imu_sensor.proto

#ifndef gz_msgs_imu_sensor
#define gz_msgs_imu_sensor

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/imu_sensor.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<IMUSensor> IMUSensorUniquePtr;
typedef std::unique_ptr<const IMUSensor> ConstIMUSensorUniquePtr;
typedef std::shared_ptr<IMUSensor> IMUSensorSharedPtr;
typedef std::shared_ptr<const IMUSensor> ConstIMUSensorSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_imu_sensor
