
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/joint_animation.proto

#ifndef gz_msgs_joint_animation
#define gz_msgs_joint_animation

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/joint_animation.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<JointAnimation> JointAnimationUniquePtr;
typedef std::unique_ptr<const JointAnimation> ConstJointAnimationUniquePtr;
typedef std::shared_ptr<JointAnimation> JointAnimationSharedPtr;
typedef std::shared_ptr<const JointAnimation> ConstJointAnimationSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_joint_animation
