
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/joystick.proto

#ifndef gz_msgs_joystick
#define gz_msgs_joystick

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/joystick.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Joystick> JoystickUniquePtr;
typedef std::unique_ptr<const Joystick> ConstJoystickUniquePtr;
typedef std::shared_ptr<Joystick> JoystickSharedPtr;
typedef std::shared_ptr<const Joystick> ConstJoystickSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_joystick
