
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/laserscan.proto

#ifndef gz_msgs_laserscan
#define gz_msgs_laserscan

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/laserscan.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<LaserScan> LaserScanUniquePtr;
typedef std::unique_ptr<const LaserScan> ConstLaserScanUniquePtr;
typedef std::shared_ptr<LaserScan> LaserScanSharedPtr;
typedef std::shared_ptr<const LaserScan> ConstLaserScanSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_laserscan
