
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/log_playback_stats.proto

#ifndef gz_msgs_log_playback_stats
#define gz_msgs_log_playback_stats

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/log_playback_stats.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<LogPlaybackStatistics> LogPlaybackStatisticsUniquePtr;
typedef std::unique_ptr<const LogPlaybackStatistics> ConstLogPlaybackStatisticsUniquePtr;
typedef std::shared_ptr<LogPlaybackStatistics> LogPlaybackStatisticsSharedPtr;
typedef std::shared_ptr<const LogPlaybackStatistics> ConstLogPlaybackStatisticsSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_log_playback_stats
