
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/parameter.proto

#ifndef gz_msgs_parameter
#define gz_msgs_parameter

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/parameter.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Parameter> ParameterUniquePtr;
typedef std::unique_ptr<const Parameter> ConstParameterUniquePtr;
typedef std::shared_ptr<Parameter> ParameterSharedPtr;
typedef std::shared_ptr<const Parameter> ConstParameterSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_parameter
