
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/particle_emitter.proto

#ifndef gz_msgs_particle_emitter
#define gz_msgs_particle_emitter

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/particle_emitter.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<ParticleEmitter> ParticleEmitterUniquePtr;
typedef std::unique_ptr<const ParticleEmitter> ConstParticleEmitterUniquePtr;
typedef std::shared_ptr<ParticleEmitter> ParticleEmitterSharedPtr;
typedef std::shared_ptr<const ParticleEmitter> ConstParticleEmitterSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_particle_emitter
