
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/plugin_v.proto

#ifndef gz_msgs_plugin_v
#define gz_msgs_plugin_v

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/plugin_v.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Plugin_V> Plugin_VUniquePtr;
typedef std::unique_ptr<const Plugin_V> ConstPlugin_VUniquePtr;
typedef std::shared_ptr<Plugin_V> Plugin_VSharedPtr;
typedef std::shared_ptr<const Plugin_V> ConstPlugin_VSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_plugin_v
