
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/propagation_grid.proto

#ifndef gz_msgs_propagation_grid
#define gz_msgs_propagation_grid

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/propagation_grid.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<PropagationGrid> PropagationGridUniquePtr;
typedef std::unique_ptr<const PropagationGrid> ConstPropagationGridUniquePtr;
typedef std::shared_ptr<PropagationGrid> PropagationGridSharedPtr;
typedef std::shared_ptr<const PropagationGrid> ConstPropagationGridSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_propagation_grid
