
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/stringmsg.proto

#ifndef gz_msgs_stringmsg
#define gz_msgs_stringmsg

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/stringmsg.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<StringMsg> StringMsgUniquePtr;
typedef std::unique_ptr<const StringMsg> ConstStringMsgUniquePtr;
typedef std::shared_ptr<StringMsg> StringMsgSharedPtr;
typedef std::shared_ptr<const StringMsg> ConstStringMsgSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_stringmsg
