
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/test.proto

#ifndef gz_msgs_test
#define gz_msgs_test

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/test.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Test> TestUniquePtr;
typedef std::unique_ptr<const Test> ConstTestUniquePtr;
typedef std::shared_ptr<Test> TestSharedPtr;
typedef std::shared_ptr<const Test> ConstTestSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_test
