
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/vector3d.proto

#ifndef gz_msgs_vector3d
#define gz_msgs_vector3d

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/vector3d.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Vector3d> Vector3dUniquePtr;
typedef std::unique_ptr<const Vector3d> ConstVector3dUniquePtr;
typedef std::shared_ptr<Vector3d> Vector3dSharedPtr;
typedef std::shared_ptr<const Vector3d> ConstVector3dSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_vector3d
