
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/version_range.proto

#ifndef gz_msgs_version_range
#define gz_msgs_version_range

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/version_range.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<VersionRange> VersionRangeUniquePtr;
typedef std::unique_ptr<const VersionRange> ConstVersionRangeUniquePtr;
typedef std::shared_ptr<VersionRange> VersionRangeSharedPtr;
typedef std::shared_ptr<const VersionRange> ConstVersionRangeSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_version_range
