
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/wheel_slip_parameters_cmd.proto

#ifndef gz_msgs_wheel_slip_parameters_cmd
#define gz_msgs_wheel_slip_parameters_cmd

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/wheel_slip_parameters_cmd.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<WheelSlipParametersCmd> WheelSlipParametersCmdUniquePtr;
typedef std::unique_ptr<const WheelSlipParametersCmd> ConstWheelSlipParametersCmdUniquePtr;
typedef std::shared_ptr<WheelSlipParametersCmd> WheelSlipParametersCmdSharedPtr;
typedef std::shared_ptr<const WheelSlipParametersCmd> ConstWheelSlipParametersCmdSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_wheel_slip_parameters_cmd
