
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/wrench.proto

#ifndef gz_msgs_wrench
#define gz_msgs_wrench

#include <memory>

#include <gz/msgs/Export.hh>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4512 4127 4068 4244 4267 4251 4146)
#endif

#include <gz/msgs/details/wrench.pb.h>

namespace gz {
namespace msgs {
typedef std::unique_ptr<Wrench> WrenchUniquePtr;
typedef std::unique_ptr<const Wrench> ConstWrenchUniquePtr;
typedef std::shared_ptr<Wrench> WrenchSharedPtr;
typedef std::shared_ptr<const Wrench> ConstWrenchSharedPtr;
}  // namespace msgs
}  // namespace gz
#ifdef _MSC_VER
#pragma warning(pop)
#endif

#endif  // gz_msgs_wrench
