/*
 * Copyright (C) 2017 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/

//                ****** Do not modify this file. ******
// This file is automatically generated by CMake. Changes should instead be
// made to cmake/gz_auto_headers.hh.in in gz-cmake

#include <gz/fuel_tools/config.hh>
#include <gz/fuel_tools/ClientConfig.hh>
#include <gz/fuel_tools/CollectionIdentifier.hh>
#include <gz/fuel_tools/FuelClient.hh>
#include <gz/fuel_tools/Helpers.hh>
#include <gz/fuel_tools/Interface.hh>
#include <gz/fuel_tools/JSONParser.hh>
#include <gz/fuel_tools/Model.hh>
#include <gz/fuel_tools/ModelIdentifier.hh>
#include <gz/fuel_tools/ModelIter.hh>
#include <gz/fuel_tools/RestClient.hh>
#include <gz/fuel_tools/Result.hh>
#include <gz/fuel_tools/WorldIdentifier.hh>
#include <gz/fuel_tools/WorldIter.hh>
#include <gz/fuel_tools/Zip.hh>

