/*
 * Copyright (C) 2022 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* Config.hh. Generated by CMake for gz-sensors. */

#ifndef GZ_SENSORS_CONFIG_HH_
#define GZ_SENSORS_CONFIG_HH_

/* Version number */
#define GZ_SENSORS_MAJOR_VERSION 8
#define GZ_SENSORS_MINOR_VERSION 0
#define GZ_SENSORS_PATCH_VERSION 0

#define GZ_SENSORS_VERSION "8.0"
#define GZ_SENSORS_VERSION_FULL "8.0.0~pre1"

#define GZ_SENSORS_VERSION_NAMESPACE v8

#define GZ_SENSORS_VERSION_HEADER "Gazebo Sensors, version 8.0.0~pre1\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

#endif
