/*
 * Copyright (C) 2017 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/

//                ****** Do not modify this file. ******
// This file is automatically generated by CMake. Changes should instead be
// made to cmake/gz_auto_headers.hh.in in gz-cmake

#include <gz/rendering/config.hh>
#include <gz/rendering/ogre/OgreArrowVisual.hh>
#include <gz/rendering/ogre/OgreAxisVisual.hh>
#include <gz/rendering/ogre/OgreCOMVisual.hh>
#include <gz/rendering/ogre/OgreCamera.hh>
#include <gz/rendering/ogre/OgreCapsule.hh>
#include <gz/rendering/ogre/OgreConversions.hh>
#include <gz/rendering/ogre/OgreDepthCamera.hh>
#include <gz/rendering/ogre/OgreDistortionPass.hh>
#include <gz/rendering/ogre/OgreDynamicLines.hh>
#include <gz/rendering/ogre/OgreDynamicRenderable.hh>
#include <gz/rendering/ogre/OgreGaussianNoisePass.hh>
#include <gz/rendering/ogre/OgreGeometry.hh>
#include <gz/rendering/ogre/OgreGizmoVisual.hh>
#include <gz/rendering/ogre/OgreGpuRays.hh>
#include <gz/rendering/ogre/OgreGrid.hh>
#include <gz/rendering/ogre/OgreHeightmap.hh>
#include <gz/rendering/ogre/OgreIncludes.hh>
#include <gz/rendering/ogre/OgreInertiaVisual.hh>
#include <gz/rendering/ogre/OgreJointVisual.hh>
#include <gz/rendering/ogre/OgreLensFlarePass.hh>
#include <gz/rendering/ogre/OgreLidarVisual.hh>
#include <gz/rendering/ogre/OgreLight.hh>
#include <gz/rendering/ogre/OgreLightVisual.hh>
#include <gz/rendering/ogre/OgreMarker.hh>
#include <gz/rendering/ogre/OgreMaterial.hh>
#include <gz/rendering/ogre/OgreMaterialSwitcher.hh>
#include <gz/rendering/ogre/OgreMesh.hh>
#include <gz/rendering/ogre/OgreMeshFactory.hh>
#include <gz/rendering/ogre/OgreNode.hh>
#include <gz/rendering/ogre/OgreObject.hh>
#include <gz/rendering/ogre/OgreObjectInterface.hh>
#include <gz/rendering/ogre/OgreParticleEmitter.hh>
#include <gz/rendering/ogre/OgreRTShaderSystem.hh>
#include <gz/rendering/ogre/OgreRayQuery.hh>
#include <gz/rendering/ogre/OgreRenderEngine.hh>
#include <gz/rendering/ogre/OgreRenderPass.hh>
#include <gz/rendering/ogre/OgreRenderTarget.hh>
#include <gz/rendering/ogre/OgreRenderTargetMaterial.hh>
#include <gz/rendering/ogre/OgreRenderTypes.hh>
#include <gz/rendering/ogre/OgreScene.hh>
#include <gz/rendering/ogre/OgreSelectionBuffer.hh>
#include <gz/rendering/ogre/OgreSensor.hh>
#include <gz/rendering/ogre/OgreStorage.hh>
#include <gz/rendering/ogre/OgreText.hh>
#include <gz/rendering/ogre/OgreThermalCamera.hh>
#include <gz/rendering/ogre/OgreVisual.hh>
#include <gz/rendering/ogre/OgreWideAngleCamera.hh>
#include <gz/rendering/ogre/OgreWireBox.hh>

