/*
 * Copyright (C) 2022 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* Config.hh. Generated by CMake for gz-physics. */

#ifndef GZ_PHYSICS_CONFIG_HH_
#define GZ_PHYSICS_CONFIG_HH_

/* Version number */
#define GZ_PHYSICS_MAJOR_VERSION 6
#define GZ_PHYSICS_MINOR_VERSION 3
#define GZ_PHYSICS_PATCH_VERSION 0

#define GZ_PHYSICS_VERSION "6.3"
#define GZ_PHYSICS_VERSION_FULL "6.3.0"

#define GZ_PHYSICS_ENGINE_INSTALL_DIR "/home/julia/workspace/install/lib/gz-physics-6/engine-plugins"

#define GZ_PHYSICS_VERSION_HEADER "Gazebo Physics, version 6.3.0\nCopyright (C) 2017 Open Source Robotics Foundation.\nReleased under the Apache 2.0 License.\n\n"

#endif
