// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/imu.proto

#ifndef PROTOBUF_INCLUDED_gz_2fmsgs_2fimu_2eproto
#define PROTOBUF_INCLUDED_gz_2fmsgs_2fimu_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "gz/msgs/header.pb.h"
#include "gz/msgs/vector3d.pb.h"
#include "gz/msgs/quaternion.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gz_2fmsgs_2fimu_2eproto IGNITION_MSGS_VISIBLE

namespace protobuf_gz_2fmsgs_2fimu_2eproto {
// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void IGNITION_MSGS_VISIBLE AddDescriptors();
}  // namespace protobuf_gz_2fmsgs_2fimu_2eproto
namespace gz {
namespace msgs {
class IMU;
class IMUDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern IMUDefaultTypeInternal _IMU_default_instance_;
}  // namespace msgs
}  // namespace gz
namespace google {
namespace protobuf {
template<> IGNITION_MSGS_VISIBLE ::gz::msgs::IMU* Arena::CreateMaybeMessage<::gz::msgs::IMU>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace gz {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE IMU : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gz.msgs.IMU) */ {
 public:
  IMU();
  virtual ~IMU();

  IMU(const IMU& from);

  inline IMU& operator=(const IMU& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IMU(IMU&& from) noexcept
    : IMU() {
    *this = ::std::move(from);
  }

  inline IMU& operator=(IMU&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const IMU& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IMU* internal_default_instance() {
    return reinterpret_cast<const IMU*>(
               &_IMU_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(IMU* other);
  friend void swap(IMU& a, IMU& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IMU* New() const final {
    return CreateMaybeMessage<IMU>(NULL);
  }

  IMU* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IMU>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IMU& from);
  void MergeFrom(const IMU& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IMU* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string entity_name = 2;
  void clear_entity_name();
  static const int kEntityNameFieldNumber = 2;
  const ::std::string& entity_name() const;
  void set_entity_name(const ::std::string& value);
  #if LANG_CXX11
  void set_entity_name(::std::string&& value);
  #endif
  void set_entity_name(const char* value);
  void set_entity_name(const char* value, size_t size);
  ::std::string* mutable_entity_name();
  ::std::string* release_entity_name();
  void set_allocated_entity_name(::std::string* entity_name);

  // .gz.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::gz::msgs::Header& _internal_header() const;
  public:
  const ::gz::msgs::Header& header() const;
  ::gz::msgs::Header* release_header();
  ::gz::msgs::Header* mutable_header();
  void set_allocated_header(::gz::msgs::Header* header);

  // .gz.msgs.Quaternion orientation = 3;
  bool has_orientation() const;
  void clear_orientation();
  static const int kOrientationFieldNumber = 3;
  private:
  const ::gz::msgs::Quaternion& _internal_orientation() const;
  public:
  const ::gz::msgs::Quaternion& orientation() const;
  ::gz::msgs::Quaternion* release_orientation();
  ::gz::msgs::Quaternion* mutable_orientation();
  void set_allocated_orientation(::gz::msgs::Quaternion* orientation);

  // .gz.msgs.Vector3d angular_velocity = 4;
  bool has_angular_velocity() const;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 4;
  private:
  const ::gz::msgs::Vector3d& _internal_angular_velocity() const;
  public:
  const ::gz::msgs::Vector3d& angular_velocity() const;
  ::gz::msgs::Vector3d* release_angular_velocity();
  ::gz::msgs::Vector3d* mutable_angular_velocity();
  void set_allocated_angular_velocity(::gz::msgs::Vector3d* angular_velocity);

  // .gz.msgs.Vector3d linear_acceleration = 5;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration();
  static const int kLinearAccelerationFieldNumber = 5;
  private:
  const ::gz::msgs::Vector3d& _internal_linear_acceleration() const;
  public:
  const ::gz::msgs::Vector3d& linear_acceleration() const;
  ::gz::msgs::Vector3d* release_linear_acceleration();
  ::gz::msgs::Vector3d* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::gz::msgs::Vector3d* linear_acceleration);

  // @@protoc_insertion_point(class_scope:gz.msgs.IMU)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr entity_name_;
  ::gz::msgs::Header* header_;
  ::gz::msgs::Quaternion* orientation_;
  ::gz::msgs::Vector3d* angular_velocity_;
  ::gz::msgs::Vector3d* linear_acceleration_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gz_2fmsgs_2fimu_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMU

// .gz.msgs.Header header = 1;
inline bool IMU::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::gz::msgs::Header& IMU::_internal_header() const {
  return *header_;
}
inline const ::gz::msgs::Header& IMU::header() const {
  const ::gz::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:gz.msgs.IMU.header)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Header*>(
      &::gz::msgs::_Header_default_instance_);
}
inline ::gz::msgs::Header* IMU::release_header() {
  // @@protoc_insertion_point(field_release:gz.msgs.IMU.header)
  
  ::gz::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::gz::msgs::Header* IMU::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.IMU.header)
  return header_;
}
inline void IMU::set_allocated_header(::gz::msgs::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.IMU.header)
}

// string entity_name = 2;
inline void IMU::clear_entity_name() {
  entity_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IMU::entity_name() const {
  // @@protoc_insertion_point(field_get:gz.msgs.IMU.entity_name)
  return entity_name_.GetNoArena();
}
inline void IMU::set_entity_name(const ::std::string& value) {
  
  entity_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gz.msgs.IMU.entity_name)
}
#if LANG_CXX11
inline void IMU::set_entity_name(::std::string&& value) {
  
  entity_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gz.msgs.IMU.entity_name)
}
#endif
inline void IMU::set_entity_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  entity_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gz.msgs.IMU.entity_name)
}
inline void IMU::set_entity_name(const char* value, size_t size) {
  
  entity_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gz.msgs.IMU.entity_name)
}
inline ::std::string* IMU::mutable_entity_name() {
  
  // @@protoc_insertion_point(field_mutable:gz.msgs.IMU.entity_name)
  return entity_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IMU::release_entity_name() {
  // @@protoc_insertion_point(field_release:gz.msgs.IMU.entity_name)
  
  return entity_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IMU::set_allocated_entity_name(::std::string* entity_name) {
  if (entity_name != NULL) {
    
  } else {
    
  }
  entity_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entity_name);
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.IMU.entity_name)
}

// .gz.msgs.Quaternion orientation = 3;
inline bool IMU::has_orientation() const {
  return this != internal_default_instance() && orientation_ != NULL;
}
inline const ::gz::msgs::Quaternion& IMU::_internal_orientation() const {
  return *orientation_;
}
inline const ::gz::msgs::Quaternion& IMU::orientation() const {
  const ::gz::msgs::Quaternion* p = orientation_;
  // @@protoc_insertion_point(field_get:gz.msgs.IMU.orientation)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Quaternion*>(
      &::gz::msgs::_Quaternion_default_instance_);
}
inline ::gz::msgs::Quaternion* IMU::release_orientation() {
  // @@protoc_insertion_point(field_release:gz.msgs.IMU.orientation)
  
  ::gz::msgs::Quaternion* temp = orientation_;
  orientation_ = NULL;
  return temp;
}
inline ::gz::msgs::Quaternion* IMU::mutable_orientation() {
  
  if (orientation_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Quaternion>(GetArenaNoVirtual());
    orientation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.IMU.orientation)
  return orientation_;
}
inline void IMU::set_allocated_orientation(::gz::msgs::Quaternion* orientation) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(orientation_);
  }
  if (orientation) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      orientation = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, orientation, submessage_arena);
    }
    
  } else {
    
  }
  orientation_ = orientation;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.IMU.orientation)
}

// .gz.msgs.Vector3d angular_velocity = 4;
inline bool IMU::has_angular_velocity() const {
  return this != internal_default_instance() && angular_velocity_ != NULL;
}
inline const ::gz::msgs::Vector3d& IMU::_internal_angular_velocity() const {
  return *angular_velocity_;
}
inline const ::gz::msgs::Vector3d& IMU::angular_velocity() const {
  const ::gz::msgs::Vector3d* p = angular_velocity_;
  // @@protoc_insertion_point(field_get:gz.msgs.IMU.angular_velocity)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Vector3d*>(
      &::gz::msgs::_Vector3d_default_instance_);
}
inline ::gz::msgs::Vector3d* IMU::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:gz.msgs.IMU.angular_velocity)
  
  ::gz::msgs::Vector3d* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
inline ::gz::msgs::Vector3d* IMU::mutable_angular_velocity() {
  
  if (angular_velocity_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Vector3d>(GetArenaNoVirtual());
    angular_velocity_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.IMU.angular_velocity)
  return angular_velocity_;
}
inline void IMU::set_allocated_angular_velocity(::gz::msgs::Vector3d* angular_velocity) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(angular_velocity_);
  }
  if (angular_velocity) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      angular_velocity = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    
  } else {
    
  }
  angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.IMU.angular_velocity)
}

// .gz.msgs.Vector3d linear_acceleration = 5;
inline bool IMU::has_linear_acceleration() const {
  return this != internal_default_instance() && linear_acceleration_ != NULL;
}
inline const ::gz::msgs::Vector3d& IMU::_internal_linear_acceleration() const {
  return *linear_acceleration_;
}
inline const ::gz::msgs::Vector3d& IMU::linear_acceleration() const {
  const ::gz::msgs::Vector3d* p = linear_acceleration_;
  // @@protoc_insertion_point(field_get:gz.msgs.IMU.linear_acceleration)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Vector3d*>(
      &::gz::msgs::_Vector3d_default_instance_);
}
inline ::gz::msgs::Vector3d* IMU::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:gz.msgs.IMU.linear_acceleration)
  
  ::gz::msgs::Vector3d* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
inline ::gz::msgs::Vector3d* IMU::mutable_linear_acceleration() {
  
  if (linear_acceleration_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Vector3d>(GetArenaNoVirtual());
    linear_acceleration_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.IMU.linear_acceleration)
  return linear_acceleration_;
}
inline void IMU::set_allocated_linear_acceleration(::gz::msgs::Vector3d* linear_acceleration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(linear_acceleration_);
  }
  if (linear_acceleration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      linear_acceleration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, linear_acceleration, submessage_arena);
    }
    
  } else {
    
  }
  linear_acceleration_ = linear_acceleration;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.IMU.linear_acceleration)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gz

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gz_2fmsgs_2fimu_2eproto
