// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/param.proto

#ifndef PROTOBUF_INCLUDED_gz_2fmsgs_2fparam_2eproto
#define PROTOBUF_INCLUDED_gz_2fmsgs_2fparam_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "gz/msgs/any.pb.h"
#include "gz/msgs/header.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gz_2fmsgs_2fparam_2eproto IGNITION_MSGS_VISIBLE

namespace protobuf_gz_2fmsgs_2fparam_2eproto {
// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void IGNITION_MSGS_VISIBLE AddDescriptors();
}  // namespace protobuf_gz_2fmsgs_2fparam_2eproto
namespace gz {
namespace msgs {
class Param;
class ParamDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern ParamDefaultTypeInternal _Param_default_instance_;
class Param_ParamsEntry_DoNotUse;
class Param_ParamsEntry_DoNotUseDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern Param_ParamsEntry_DoNotUseDefaultTypeInternal _Param_ParamsEntry_DoNotUse_default_instance_;
}  // namespace msgs
}  // namespace gz
namespace google {
namespace protobuf {
template<> IGNITION_MSGS_VISIBLE ::gz::msgs::Param* Arena::CreateMaybeMessage<::gz::msgs::Param>(Arena*);
template<> IGNITION_MSGS_VISIBLE ::gz::msgs::Param_ParamsEntry_DoNotUse* Arena::CreateMaybeMessage<::gz::msgs::Param_ParamsEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace gz {
namespace msgs {

// ===================================================================

class Param_ParamsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Param_ParamsEntry_DoNotUse, 
    ::std::string, ::gz::msgs::Any,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Param_ParamsEntry_DoNotUse, 
    ::std::string, ::gz::msgs::Any,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Param_ParamsEntry_DoNotUse();
  Param_ParamsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Param_ParamsEntry_DoNotUse& other);
  static const Param_ParamsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Param_ParamsEntry_DoNotUse*>(&_Param_ParamsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class IGNITION_MSGS_VISIBLE Param : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gz.msgs.Param) */ {
 public:
  Param();
  virtual ~Param();

  Param(const Param& from);

  inline Param& operator=(const Param& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Param(Param&& from) noexcept
    : Param() {
    *this = ::std::move(from);
  }

  inline Param& operator=(Param&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Param& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Param* internal_default_instance() {
    return reinterpret_cast<const Param*>(
               &_Param_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Param* other);
  friend void swap(Param& a, Param& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Param* New() const final {
    return CreateMaybeMessage<Param>(NULL);
  }

  Param* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Param>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Param& from);
  void MergeFrom(const Param& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Param* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .gz.msgs.Any> params = 2;
  int params_size() const;
  void clear_params();
  static const int kParamsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::gz::msgs::Any >&
      params() const;
  ::google::protobuf::Map< ::std::string, ::gz::msgs::Any >*
      mutable_params();

  // repeated .gz.msgs.Param children = 3;
  int children_size() const;
  void clear_children();
  static const int kChildrenFieldNumber = 3;
  ::gz::msgs::Param* mutable_children(int index);
  ::google::protobuf::RepeatedPtrField< ::gz::msgs::Param >*
      mutable_children();
  const ::gz::msgs::Param& children(int index) const;
  ::gz::msgs::Param* add_children();
  const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Param >&
      children() const;

  // .gz.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::gz::msgs::Header& _internal_header() const;
  public:
  const ::gz::msgs::Header& header() const;
  ::gz::msgs::Header* release_header();
  ::gz::msgs::Header* mutable_header();
  void set_allocated_header(::gz::msgs::Header* header);

  // @@protoc_insertion_point(class_scope:gz.msgs.Param)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      Param_ParamsEntry_DoNotUse,
      ::std::string, ::gz::msgs::Any,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > params_;
  ::google::protobuf::RepeatedPtrField< ::gz::msgs::Param > children_;
  ::gz::msgs::Header* header_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gz_2fmsgs_2fparam_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Param

// .gz.msgs.Header header = 1;
inline bool Param::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::gz::msgs::Header& Param::_internal_header() const {
  return *header_;
}
inline const ::gz::msgs::Header& Param::header() const {
  const ::gz::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:gz.msgs.Param.header)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Header*>(
      &::gz::msgs::_Header_default_instance_);
}
inline ::gz::msgs::Header* Param::release_header() {
  // @@protoc_insertion_point(field_release:gz.msgs.Param.header)
  
  ::gz::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::gz::msgs::Header* Param::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.Param.header)
  return header_;
}
inline void Param::set_allocated_header(::gz::msgs::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.Param.header)
}

// map<string, .gz.msgs.Any> params = 2;
inline int Param::params_size() const {
  return params_.size();
}
inline const ::google::protobuf::Map< ::std::string, ::gz::msgs::Any >&
Param::params() const {
  // @@protoc_insertion_point(field_map:gz.msgs.Param.params)
  return params_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::gz::msgs::Any >*
Param::mutable_params() {
  // @@protoc_insertion_point(field_mutable_map:gz.msgs.Param.params)
  return params_.MutableMap();
}

// repeated .gz.msgs.Param children = 3;
inline int Param::children_size() const {
  return children_.size();
}
inline void Param::clear_children() {
  children_.Clear();
}
inline ::gz::msgs::Param* Param::mutable_children(int index) {
  // @@protoc_insertion_point(field_mutable:gz.msgs.Param.children)
  return children_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::gz::msgs::Param >*
Param::mutable_children() {
  // @@protoc_insertion_point(field_mutable_list:gz.msgs.Param.children)
  return &children_;
}
inline const ::gz::msgs::Param& Param::children(int index) const {
  // @@protoc_insertion_point(field_get:gz.msgs.Param.children)
  return children_.Get(index);
}
inline ::gz::msgs::Param* Param::add_children() {
  // @@protoc_insertion_point(field_add:gz.msgs.Param.children)
  return children_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Param >&
Param::children() const {
  // @@protoc_insertion_point(field_list:gz.msgs.Param.children)
  return children_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gz

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gz_2fmsgs_2fparam_2eproto
