// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gz/msgs/twist.proto

#ifndef PROTOBUF_INCLUDED_gz_2fmsgs_2ftwist_2eproto
#define PROTOBUF_INCLUDED_gz_2fmsgs_2ftwist_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "gz/msgs/vector3d.pb.h"
#include "gz/msgs/header.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gz_2fmsgs_2ftwist_2eproto IGNITION_MSGS_VISIBLE

namespace protobuf_gz_2fmsgs_2ftwist_2eproto {
// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void IGNITION_MSGS_VISIBLE AddDescriptors();
}  // namespace protobuf_gz_2fmsgs_2ftwist_2eproto
namespace gz {
namespace msgs {
class Twist;
class TwistDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern TwistDefaultTypeInternal _Twist_default_instance_;
}  // namespace msgs
}  // namespace gz
namespace google {
namespace protobuf {
template<> IGNITION_MSGS_VISIBLE ::gz::msgs::Twist* Arena::CreateMaybeMessage<::gz::msgs::Twist>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace gz {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE Twist : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gz.msgs.Twist) */ {
 public:
  Twist();
  virtual ~Twist();

  Twist(const Twist& from);

  inline Twist& operator=(const Twist& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Twist(Twist&& from) noexcept
    : Twist() {
    *this = ::std::move(from);
  }

  inline Twist& operator=(Twist&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Twist& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Twist* internal_default_instance() {
    return reinterpret_cast<const Twist*>(
               &_Twist_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Twist* other);
  friend void swap(Twist& a, Twist& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Twist* New() const final {
    return CreateMaybeMessage<Twist>(NULL);
  }

  Twist* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Twist>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Twist& from);
  void MergeFrom(const Twist& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Twist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .gz.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::gz::msgs::Header& _internal_header() const;
  public:
  const ::gz::msgs::Header& header() const;
  ::gz::msgs::Header* release_header();
  ::gz::msgs::Header* mutable_header();
  void set_allocated_header(::gz::msgs::Header* header);

  // .gz.msgs.Vector3d linear = 2;
  bool has_linear() const;
  void clear_linear();
  static const int kLinearFieldNumber = 2;
  private:
  const ::gz::msgs::Vector3d& _internal_linear() const;
  public:
  const ::gz::msgs::Vector3d& linear() const;
  ::gz::msgs::Vector3d* release_linear();
  ::gz::msgs::Vector3d* mutable_linear();
  void set_allocated_linear(::gz::msgs::Vector3d* linear);

  // .gz.msgs.Vector3d angular = 3;
  bool has_angular() const;
  void clear_angular();
  static const int kAngularFieldNumber = 3;
  private:
  const ::gz::msgs::Vector3d& _internal_angular() const;
  public:
  const ::gz::msgs::Vector3d& angular() const;
  ::gz::msgs::Vector3d* release_angular();
  ::gz::msgs::Vector3d* mutable_angular();
  void set_allocated_angular(::gz::msgs::Vector3d* angular);

  // @@protoc_insertion_point(class_scope:gz.msgs.Twist)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::gz::msgs::Header* header_;
  ::gz::msgs::Vector3d* linear_;
  ::gz::msgs::Vector3d* angular_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gz_2fmsgs_2ftwist_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Twist

// .gz.msgs.Header header = 1;
inline bool Twist::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::gz::msgs::Header& Twist::_internal_header() const {
  return *header_;
}
inline const ::gz::msgs::Header& Twist::header() const {
  const ::gz::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:gz.msgs.Twist.header)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Header*>(
      &::gz::msgs::_Header_default_instance_);
}
inline ::gz::msgs::Header* Twist::release_header() {
  // @@protoc_insertion_point(field_release:gz.msgs.Twist.header)
  
  ::gz::msgs::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::gz::msgs::Header* Twist::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.Twist.header)
  return header_;
}
inline void Twist::set_allocated_header(::gz::msgs::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.Twist.header)
}

// .gz.msgs.Vector3d linear = 2;
inline bool Twist::has_linear() const {
  return this != internal_default_instance() && linear_ != NULL;
}
inline const ::gz::msgs::Vector3d& Twist::_internal_linear() const {
  return *linear_;
}
inline const ::gz::msgs::Vector3d& Twist::linear() const {
  const ::gz::msgs::Vector3d* p = linear_;
  // @@protoc_insertion_point(field_get:gz.msgs.Twist.linear)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Vector3d*>(
      &::gz::msgs::_Vector3d_default_instance_);
}
inline ::gz::msgs::Vector3d* Twist::release_linear() {
  // @@protoc_insertion_point(field_release:gz.msgs.Twist.linear)
  
  ::gz::msgs::Vector3d* temp = linear_;
  linear_ = NULL;
  return temp;
}
inline ::gz::msgs::Vector3d* Twist::mutable_linear() {
  
  if (linear_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Vector3d>(GetArenaNoVirtual());
    linear_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.Twist.linear)
  return linear_;
}
inline void Twist::set_allocated_linear(::gz::msgs::Vector3d* linear) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(linear_);
  }
  if (linear) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      linear = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, linear, submessage_arena);
    }
    
  } else {
    
  }
  linear_ = linear;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.Twist.linear)
}

// .gz.msgs.Vector3d angular = 3;
inline bool Twist::has_angular() const {
  return this != internal_default_instance() && angular_ != NULL;
}
inline const ::gz::msgs::Vector3d& Twist::_internal_angular() const {
  return *angular_;
}
inline const ::gz::msgs::Vector3d& Twist::angular() const {
  const ::gz::msgs::Vector3d* p = angular_;
  // @@protoc_insertion_point(field_get:gz.msgs.Twist.angular)
  return p != NULL ? *p : *reinterpret_cast<const ::gz::msgs::Vector3d*>(
      &::gz::msgs::_Vector3d_default_instance_);
}
inline ::gz::msgs::Vector3d* Twist::release_angular() {
  // @@protoc_insertion_point(field_release:gz.msgs.Twist.angular)
  
  ::gz::msgs::Vector3d* temp = angular_;
  angular_ = NULL;
  return temp;
}
inline ::gz::msgs::Vector3d* Twist::mutable_angular() {
  
  if (angular_ == NULL) {
    auto* p = CreateMaybeMessage<::gz::msgs::Vector3d>(GetArenaNoVirtual());
    angular_ = p;
  }
  // @@protoc_insertion_point(field_mutable:gz.msgs.Twist.angular)
  return angular_;
}
inline void Twist::set_allocated_angular(::gz::msgs::Vector3d* angular) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(angular_);
  }
  if (angular) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      angular = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, angular, submessage_arena);
    }
    
  } else {
    
  }
  angular_ = angular;
  // @@protoc_insertion_point(field_set_allocated:gz.msgs.Twist.angular)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gz

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gz_2fmsgs_2ftwist_2eproto
